Update Process.ts
Blockception/BC-Minecraft-Bedrock-Project pull request #144
Opened 2024-06-29 13:32 UTC by Xterionix

Resolve https://github.com/Blockception/BC-Minecraft-Bedrock-Diagnoser/issues/217

2024-06-29 13:58 UTC, DaanV2 requested changes
I think we are going to need to do this differently, and here is why it going to suck 😬 


Cause you can have the following:

```
geometry.namespace:name:geometry.namespace:other_name
```

So we might need to split on `:geometry` and then fixup 🤔

2024-06-29 14:00 UTC, Xterionix commented
Ah yeah, you're right

2024-06-29 18:47 UTC, Xterionix commented
![image](https://github.com/Blockception/BC-Minecraft-Bedrock-Project/assets/72647213/1cdf8a85-6d7e-4e9e-9173-b1ada5581072)

2024-07-01 19:05 UTC, DaanV2 approved these changes

2024-07-01 19:05 UTC, merged